#!/usr/bin/env php
<?
require '../CLIAbstraction.php';

class ExampleProgram implements CliProgram {

	public static function main($args) {
		$togo = '';

		// Use it as key-valued arrays
		if ( isset( $args['to-go'] ) ) {
			$togo = " to go..";
		}

		$potato = $args['potato'];

		print "You asked for {$potato} potatoes{$togo}.";
	}

	// This are your params configurations: keys for shorthands, values for params
	public static function getParams() {
		return array( 'p' => 'potato', 'to-go' );
	}
}

// Black magic
run();