#!/usr/bin/env php
<?
require '../CliParamsAbstraction.php';

class ExampleProgram implements CliProgram {
	public static function main($args) {
		print "Hello, Command Line World!";

		$togo = '';
		if ( isset( $args['to-go'] ) ) {
            $togo = " to go..";
        }

        $potato = $args['potato'];

        print PHP_EOL . "You asked for {$potato} potatoes{$togo}." . PHP_EOL;
	}
}

// Must be in your code
try {
	CliParamsAbstraction::init('ExampleProgram', $argv, array( 'p' => 'potato', 'to-go' ) );
} catch (Exception $e) {
	print "Error: " . $e->getMessage();
}